CREATE DATABASE SoftUni

CREATE TABLE Towns (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	AddressText NVARCHAR(1000) NOT NULL, 
	TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)	
	
CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	FirstName NVARCHAR(30) NOT NULL, 
	MiddleName NVARCHAR(30), 
	LastName NVARCHAR(30) NOT NULL, 
	JobTitle NVARCHAR(20) NOT NULL, 
	DepartmentId INT NOT NULL
	FOREIGN KEY REFERENCES Departments(Id), 
	HireDate DATE NOT NULL, 
	Salary DECIMAL(7,2), 
	AddressId INT NOT NULL
	FOREIGN KEY REFERENCES Addresses(Id)
)

